services:
  - type: web
    name: football-challenge
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: MYSQL_HOST
        value: localhost
      - key: MYSQL_USER
        value: root
      - key: MYSQL_PASSWORD
        value: Maharshi@2004
      - key: MYSQL_DATABASE
        value: football_challenge
